#!/usr/bin/env python3
"""Build the CamCore production DNS blocklist from the approved upstream feed."""

from __future__ import annotations

import ipaddress
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "camcore/sources.json"
ALLOWLIST = ROOT / "camcore/allowlist.txt"
DENYLIST = ROOT / "camcore/denylist.txt"
OUTPUT = ROOT / "blocklist.txt"
MAX_BYTES = 20 * 1024 * 1024
MIN_ENTRIES = 10000
USER_AGENT = "CamCore-DNS-Publisher/1.0 (+https://github.com/camcoreau/dns-blocklists)"
PROTECTED_SUFFIXES = ("camcore.au", "camcore.network", "localhost", "local", "lan", "home.arpa")
LABEL_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


def valid_domain(value: str) -> bool:
    if not value or value != value.lower() or len(value) > 253:
        return False
    if value.startswith(".") or value.endswith(".") or any(x in value for x in ("://", "/", ":", "*", " ")):
        return False
    try:
        ipaddress.ip_address(value)
        return False
    except ValueError:
        pass
    labels = value.split(".")
    return len(labels) >= 2 and all(LABEL_RE.fullmatch(label) for label in labels)


def read_local(path: Path) -> set[str]:
    values: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        value = raw.strip()
        if not value or value.startswith("#"):
            continue
        if not valid_domain(value):
            raise RuntimeError(f"Invalid local domain in {path}: {value!r}")
        values.add(value)
    return values


def production_source() -> dict[str, object]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    active = [s for s in manifest["sources"] if s.get("status") == "active" and s.get("deployment") == "production"]
    if len(active) != 1:
        raise RuntimeError(f"Expected exactly one production source, found {len(active)}")
    source = active[0]
    if source.get("id") != "camcore-hagezi-multi-normal":
        raise RuntimeError("Unexpected production source identity")
    return source


def fetch_domains(url: str) -> set[str]:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT, "Accept": "text/plain"})
    with urllib.request.urlopen(request, timeout=60) as response:
        if response.geturl().split(":", 1)[0] != "https":
            raise RuntimeError("Upstream redirected away from HTTPS")
        raw = response.read(MAX_BYTES + 1)
    if len(raw) > MAX_BYTES:
        raise RuntimeError("Upstream feed exceeded the 20 MiB safety limit")
    text = raw.decode("utf-8")
    domains: set[str] = set()
    for number, raw_line in enumerate(text.splitlines(), 1):
        line = raw_line.strip().lower()
        if not line or line.startswith(("#", "!")):
            continue
        if not valid_domain(line):
            raise RuntimeError(f"Unexpected upstream entry at line {number}: {raw_line!r}")
        domains.add(line)
    if len(domains) < MIN_ENTRIES:
        raise RuntimeError(f"Upstream feed contained only {len(domains)} valid domains; refusing to replace last-known-good output")
    return domains


def protected(domain: str) -> bool:
    return any(domain == suffix or domain.endswith(f".{suffix}") for suffix in PROTECTED_SUFFIXES)


def main() -> int:
    source = production_source()
    upstream_url = source.get("upstream_url")
    if not isinstance(upstream_url, str) or not upstream_url.startswith("https://"):
        raise RuntimeError("Production source must define an HTTPS upstream_url")

    domains = fetch_domains(upstream_url)
    allow = read_local(ALLOWLIST)
    deny = read_local(DENYLIST)

    domains.difference_update(allow)
    domains.update(deny)
    domains = {domain for domain in domains if not protected(domain)}

    lines = [
        "# CamCore DNS Blocklist",
        "# Production feed for CamCore-managed Pi-hole resolvers.",
        "# Source: HaGeZi Multi NORMAL; CamCore allow/deny policy applied.",
        "# Generated automatically. Do not edit this file manually.",
        "",
        *sorted(domains),
    ]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Published {len(domains)} domains to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
